baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
baseURL = "https://hopzoomhtc-dev.github.io/htc-news/"
languageCode = "vi-vn"
title = "HTC News"

theme = "PaperMod"
